const TABLE_NAME = 'AM1002'

export const QUERY_CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  SERIAL_NUMBER TEXT NOT NULL,
  TIMESTAMP TEXT NOT NULL,
  TVOC INTEGER NOT NULL,
  PN_1P0 INTEGER NOT NULL,
  PN_2P5 INTEGER NOT NULL,
  PN_10P INTEGER NOT NULL,
  TEMPERATURE REAL NOT NULL,
  HUMIDITY REAL NOT NULL
)`

export const QUERY_INSERT_INTO = `
INSERT INTO ${TABLE_NAME} (
  SERIAL_NUMBER,
  TIMESTAMP,
  TVOC,
  PN_1P0,
  PN_2P5,
  PN_10P,
  TEMPERATURE,
  HUMIDITY
)
VALUES(?, ?, ?, ?, ?, ?, ?, ?)
`

export const QUERY_GET_SERIAL_NUMBERS = `SELECT DISTINCT SERIAL_NUMBER FROM ${TABLE_NAME} ORDER BY SERIAL_NUMBER ASC;`

export const QUERY_GET_DATA: (serialNumber: string) => string = (serialNumber) =>
  `
SELECT
  ID,
  TIMESTAMP,
  TVOC,
  PN_1P0,
  PN_2P5,
  PN_10P,
  TEMPERATURE,
  HUMIDITY
FROM ${TABLE_NAME}
WHERE SERIAL_NUMBER = "${serialNumber}"
ORDER BY ID DESC
LIMIT 1000`
