export const CMD_READ_MEASURED_CO2_RESULT = 0x01
export const CMD_SET_ABC = 0x10
export const CMD_CALIBRATE_CONCENTRATION_CO2_VALUE = 0x03
export const CMD_READ_SERIAL_NUMBER = 0x1f
export const CMD_READ_SOFTWARE_VERSION_NUMBER = 0x1e
