const TABLE_NAME = 'CM1107'

export const QUERY_CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  SERIAL_NUMBER TEXT NOT NULL,
  TIMESTAMP TEXT NOT NULL,
  CO2 INTEGER NOT NULL
)`

export const QUERY_INSERT_INTO = `
INSERT INTO ${TABLE_NAME} (
  SERIAL_NUMBER,
  TIMESTAMP,
  CO2
)
VALUES(?, ?, ?)
`

export const QUERY_GET_SERIAL_NUMBERS = `SELECT DISTINCT SERIAL_NUMBER FROM ${TABLE_NAME} ORDER BY SERIAL_NUMBER ASC;`

export const QUERY_GET_DATA: (serialNumber: string) => string = (serialNumber) =>
  `
SELECT
  ID,
  TIMESTAMP,
  CO2
FROM ${TABLE_NAME}
WHERE SERIAL_NUMBER = "${serialNumber}"
ORDER BY ID DESC
LIMIT 1000`
