const TABLE_NAME = 'CM1107'

export const QUERY_CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  SERIAL_NUMBER TEXT NOT NULL,
  TIMESTAMP TEXT NOT NULL,
  CO2 INTEGER NOT NULL
)`

export const QUERY_INSERT_INTO = `
INSERT INTO ${TABLE_NAME} (
  SERIAL_NUMBER,
  TIMESTAMP,
  CO2
)
VALUES(?, ?, ?)
`
